config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1, defaults: {format: 'json'} do
      resources :webhook, only: [:create, :index], constraints: { format: 'json' } 
    end
  end
  root 'request#index'  
  resources :request  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/api/v1/webhook_controller.rb
class Api::V1::WebhookController < ApplicationController
  protect_from_forgery with: :null_session
  def index
    render json: {data: 'Listening...'}
  end

  def create
    params[:type] == "" ? type = "users" : type = params[:type]
    params[:filter_type] == "" ? ftype = nil : ftype = params[:filter_type]
    params[:filter_keyword] == "" ? fkw = nil : fkw = params[:filter_keyword]
    params[:page_size] == "" ? psize = nil : psize = params[:page_size]
    
    @webhook = ApiService.get_teamtailor_response(type, ftype, fkw, psize)
    File.open("./webhook.yaml", "w") { |file| file.write(@webhook.to_yaml) }

    render json: {data: 'All good.'}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/request_controller.rb
class RequestController < ApplicationController
  require 'json'
  require 'yaml'

  def index
    webhook = YAML.load_file('./webhook.yaml') 
    store = YAML.load_file('./store.yaml')
    @response = store
    @webhook = webhook
  end

  def new
  end

  def show
  end

  def create

    params[:type] == "" ? type = "users" : type = params[:type]
    params[:filter_type] == "" ? ftype = nil : ftype = params[:filter_type]
    params[:filter_keyword] == "" ? fkw = nil : fkw = params[:filter_keyword]
    params[:page_size] == "" ? psize = nil : psize = params[:page_size]

    @response = ApiService.get_teamtailor_response(type, ftype, fkw, psize)
    File.open("./store.yaml", "w") { |file| file.write(@response.to_yaml) }
    redirect_to root_path
  end
   
end

app/helpers/api/v1/webhook_helper.rb
module Api::V1::WebhookHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teamtailor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/request/_new.html.erb
<div class="container mx-auto mt-12 ">

<%= form_with url: request_index_path, method: :post do |form| %>
  <%= form.label :type, class: "block text-grey-darker text-sm font-bold mb-2" %>
  <%= form.text_field :type, class: "shadow appearance-none border rounded mb-4 py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"%>
  <%= form.label :filter_type, class: "block text-grey-darker text-sm font-bold mb-2" %>
  <%= form.text_field :filter_type, class: "shadow appearance-none border mb-4 rounded py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"%>
  <%= form.label :filter_key_word, class: "block text-grey-darker text-sm font-bold mb-2" %>
  <%= form.text_field :filter_keyword, class: "shadow appearance-none border mb-4 rounded py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"%>
  <%= form.label :page_size, class: "block text-grey-darker text-sm font-bold mb-2" %>
  <%= form.text_field :page_size, class: "shadow appearance-none border rounded py-2 px-3 mb-4 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"%>
  <%= form.submit value: "GET", class: "bg-blue ml-4 hover:bg-blue-dark text-white font-bold py-2 px-4 my-4 rounded focus:outline-none focus:shadow-outline"%>
<% end %>

</div>

app/views/request/_show.html.erb
<div class="container mx-auto mt-12">
  
</div>

app/views/request/index.html.erb
<div class="container mx-auto mt-10 border rounded overflow-hidden p-4">
  <h2> Team Tailor API</h2>
  <%= render partial: "new" %>
  <br />
  <h3> Response</h3>
  <br />
  <pre class="text-xs"><%= JSON.pretty_generate(@webhook) %><pre>
  <pre class="text-xs"><%= JSON.pretty_generate(@response) %><pre>
</div>